### PR TITLE
commit after class and DFT complete.

### PR DESCRIPTION
**Pull request by lcampbe79**
Forgot to commit after class but have DFT working.

### CODE REVIEW

**Comment by lcampbe79** [comment]
(84c3add) had to add visited=None as a parameter or else I would get a recursion error.

**Comment by lcampbe79** [comment]
(4937830) Updated dft_recursive header function from 
```
visited=None
```
to 
```
visited=set()
```
but kept the if statement in case we use it that way tomorrow. If visited was not added as a parameter then I would get a recursion error.

**Comment by lcampbe79** [comment]
Changed the argument in the dft_recursive back to 
```
visited=None
```
due to [common python gotchas](https://docs.python-guide.org/writing/gotchas/)

**Comment by lcampbe79** [comment]
(fadee47) Need to write more comments regarding understanding everything in the dfs_recursive function tomorrow.

**Review by gisturiz — APPROVED** [review]

**Pull request merged**
